version: '3.4'

services:
  vivethereeshopweb:
    image: vivethereacr0117cls2.azurecr.io/vivethereeshopweb:v1
    ports:
        - "80:80"
        - "443:443"
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    container_name: vivethereeshopweb
        
    
    
  vivetherepublicapi:
    image: vivethereacr0117cls2.azurecr.io/vivetherepublicapi:v1
    ports:
        - "80:80"
        - "443:443"
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    container_name: vivetherepublicapi


